FROM node:22-alpine AS frontend

WORKDIR /var/www/html

COPY package.json package-lock.json ./

RUN npm ci --no-audit --no-fund

COPY resources ./resources
COPY vite.config.js ./vite.config.js

RUN npm run build

FROM nginx:stable-alpine

COPY docker/nginx/default.prod.conf /etc/nginx/conf.d/default.conf
COPY public /var/www/html/public
COPY --from=frontend /var/www/html/public/build /var/www/html/public/build

EXPOSE 80
EXPOSE 443
